name: build and deploy

# master 分支 push 代码时触发 workflow
on:
  push:
    branches:
      - master

jobs:
  main:
    runs-on: ubuntu-latest
    setps:
      # 拉取github仓库代码
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      # 执行依赖安装
      - name: 安装依赖
        run: pnpm install

      # 打包构建
      - name: 构建
        run: pnpm run build

      # 执行部署
      - name: 部署
        uses: JamesIves/github-pages-deploy-action@releases/v3 # 这个action会根据配置自动推送代码到指定分支
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }} # 指定密钥
          BRANCH: gh-pages ##指定推送到的远程分支
          FOLDER: /dist # 指定构建之后要推送哪个目录的代码
