name: build and deploy

# master 分支 push 代码时触发 workflow
on:
  push:
    branches:
      - master

jobs:
  push-to-gh-pages:
    runs-on: ubuntu-latest
    setps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          yarn install
          yarn run build

      # 执行部署
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }} # 指定密钥
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./dist
        with:
          forceOrphan: true
